### ISSUE TITLE
Would be happy to adopt

### ISSUE THREAD

**Issue by xaranke** [xaranke/chroniton#24]
This is something I've been looking to make for a while now. 
Instead of creating a new library I'd be happy to adopt this one and give it a fresh coat of paint.

Let me know what you think.
Thanks!

**Comment by tmcw** [comment]
Excellent!

* [ ] @tmcw requests a transfer from tmcw-up-for-adoption to @xaranke 
* [ ] @tmcw adds you to the npm owners for https://www.npmjs.com/package/chroniton - npm username: xaranke
